### ISSUE TITLE
Ignore specific paths

### ISSUE THREAD

**Issue by yeldarby** [why2pac/express-naked-redirect#2]
Is there a way to have `express-naked-redirect` apply to everything except a specific path? I'm having an issue with `letsencrypt` certificate renewals because it needs to access `/.well-known/` on `http` port 80.

If I disable `express-naked-redirect` my certificate renewal works. But when it's enabled it fails because it doesn't like the 301 response.

**Comment by why2pac** [comment]
Version 0.1.2, add `except` option for do not redirect specific paths. You can use this option.

**Comment by yeldarby** [comment]
Excellent! Thanks
