### ISSUE TITLE
Reverse proxies (Heroku, Elastic Beanstalk, etc.)

### ISSUE THREAD

**Issue by yn5** [why2pac/express-naked-redirect#3]
Just as a suggestion. It would be great to have a flag where you can trust the x-forwarded-proto header set by proxies like in this package: https://github.com/florianheinemann/express-sslify#reverse-proxies-heroku-nodejitsu-and-others
This way, I could drop the dependency for that package and just use this one.

**Comment by raycharius** [comment]
You could check out https://github.com/raycharius/clean-redirect – takes all of those redirects and does them in one, with the option of adding your own custom logic to the redirect on top

**Comment by yn5** [comment]
I guess that solves it then, thanks @raycharius!
