### ISSUE TITLE
Can't resolve 'url-pattern'

### ISSUE THREAD

**Issue by gorkemyontem** [why2pac/express-naked-redirect#4]
Hi there,
I'm getting Can't resolve 'url-pattern' error. 
I think 'url-pattern' should be in dependencies instead of devDependencies. 

What you think? @why2pac

**Comment by why2pac** [comment]
Hi There!,
'devDependencies' is right. 'url-pattern' is not included by default. You should install it manually. Please refer to README.md.
Thanks!

**Comment by gorkemyontem** [comment]
Thanks for quick replay @why2pac,
Sorry, I missed its section in the readme file. 

Just for let you know, webpack is warning me about this file even if it's not required. I think it's a bit annoying. Oh, I might be the only one who use this library as a part of an universal (SSR) angular project. Then it's my problem:)

**Comment by why2pac** [comment]
I missed webpack warning. I have to look into details. Thanks!
